name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu_latest
        steps:
            - name: Welcome message
              run: echo "First GitHub Action Job !"
            
            - name: List files
              run: ls

            - name: Read file
              run: cat README.md
              
        